from . import hr_payslip_custom
from . import salaries_excel_sheet
from . import hr_employee
from . import employee_loan
from . import stock_location
from . import confirmation_evaluation
from . import assessment_criteria
from . import training_plans
from . import training_feedback_form
from . import confirmation_evaluation_reject_wizard
from . import exit_interview_from
from . import resignation_reason
from . import exit_development_experience
from . import hr_leave_request
from . import skilled_workers
from . import labors
from . import overtime_guide
from . import res_company