# -*- coding: utf-8 -*-

{
    'name': 'Fastra HR Customize',
    'version': '12.0.1.0.0',
    'summary': 'Fastra HR Customize',
    'depends': ['hr', 'stock', 'account', 'hr_menus', 'hr_timesheet', 'hr_expense'],
    'data': [
        'security/ir.model.access.csv',
        'security/hr_customize_security.xml',
        'data/payroll_sequence.xml',

        'views/hr_payslip_custom.xml',
        'views/salaries_excel_sheet.xml',
        'views/employee_loan.xml',
        'views/stock_location.xml',
        'views/confirmation_evaluation.xml',
        'views/assessment_criteria.xml',
        'views/training_plans.xml',
        'views/training_feedback_form.xml',
        'views/casual_worker.xml',
        'views/confirmation_evaluation_reject_wizard.xml',
        'views/exit_interview_from.xml',
        'views/resignation_reason.xml',
        'views/exit_development_experience.xml',
        'views/hr_leave_request.xml',
        'views/hr_contract_view_inherit.xml',
        'views/skilled_workers.xml',
        'views/labors.xml',
        'views/overtime_guide.xml',
        'views/res_company.xml',
        'views/hr_employee.xml',

        'reports/salaries_excel_sheet_report.xml',
        'reports/payroll_report.xml',
        'reports/training_feedback_report.xml',
        'reports/skilled_workers_report.xml',
        'reports/hr_labors_report.xml',
        'reports/overtime_guide_report.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
