{
    'name': 'Material Consumption',
    'version': '12.0.1',
    'category': 'Inventory',
    'summary': 'Material consumption',
    'author': 'TAXDOTCOM',
    'website': 'http://taxdotcom.org/',
    'maintainer': 'Muhammad Younis',
    'depends': ['stock_account', 'stock', 'uom', 'product', 'project_costing'],
    'data': [
        'security/ir.model.access.csv',
        'views/stock_inventory.xml',
        'views/product.xml',
        'data/ir_sequence.xml',
        'data/stock_location.xml',
        'wizard/display_message.xml',
    ],
    'installable': True,
    'auto_install': False,
    'price': 20.00,
    'currency': 'EUR',
    # 'images': ['static/description/icon.png'],
    'license': 'OPL-1',
}
